// Automatically generated from C:/Users/lumia/Desktop/WebKit/Source/JavaScriptCore/runtime/TemporalDurationPrototype.cpp using C:/Users/lumia/Desktop/WebKit/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static const struct CompactHashIndex durationPrototypeTableIndex[69] = {
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, -1 },
    { 9, 66 },
    { 22, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 1, -1 },
    { -1, -1 },
    { 5, 64 },
    { 7, 67 },
    { -1, -1 },
    { 13, 68 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 8, -1 },
    { 18, -1 },
    { -1, -1 },
    { -1, -1 },
    { 15, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { 4, 65 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { 16, -1 },
    { 19, -1 },
    { 20, -1 },
    { 21, -1 },
};

static const struct HashTableValue durationPrototypeTableValues[23] = {
   { "with", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncWith), (intptr_t)(1) } },
   { "negated", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncNegated), (intptr_t)(0) } },
   { "abs", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncAbs), (intptr_t)(0) } },
   { "add", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncAdd), (intptr_t)(1) } },
   { "subtract", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncSubtract), (intptr_t)(1) } },
   { "round", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncRound), (intptr_t)(1) } },
   { "total", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncTotal), (intptr_t)(1) } },
   { "toString", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncToString), (intptr_t)(0) } },
   { "toJSON", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncToJSON), (intptr_t)(0) } },
   { "toLocaleString", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncToLocaleString), (intptr_t)(0) } },
   { "valueOf", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(temporalDurationPrototypeFuncValueOf), (intptr_t)(0) } },
   { "years", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterYears), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "months", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterMonths), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "weeks", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterWeeks), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "days", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterDays), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "hours", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterHours), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "minutes", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterMinutes), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "seconds", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterSeconds), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "milliseconds", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterMilliseconds), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "microseconds", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterMicroseconds), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "nanoseconds", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterNanoseconds), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "sign", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterSign), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "blank", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(temporalDurationPrototypeGetterBlank), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
};

static const struct HashTable durationPrototypeTable =
    { 23, 63, true, nullptr, durationPrototypeTableValues, durationPrototypeTableIndex };

} // namespace JSC
